import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "~/db/connection.server";
import * as authSchema from "../db/schema/auth-schema"   // file generated by the CLI


export const auth = betterAuth({
    emailAndPassword: {
        enabled: true,
    },
    database: drizzleAdapter(db, {
        schema: authSchema,
        provider: "pg"
    }),
});
